### ISSUE TITLE
Scroll bar is not greyed out when there is not enough items to scroll

### ISSUE THREAD

**Issue by EnderLord0042** [samolego/ClientStorage#10]
In the creative mode inventory, the scroll bar gets greyed out when there is not enough items to scroll.
![2022-10-20_17 32 11](https://user-images.githubusercontent.com/55165281/197084525-e27340e9-ee6d-47ce-9db7-bc11686bf46c.png)

However, this behavior is not present in ClientStorage.
![2022-10-20_17 31 44](https://user-images.githubusercontent.com/55165281/197084577-a1977fb2-a3e8-4c32-b385-723c48ba0542.png)

**Comment by samolego** [comment]
Wow, didn't even know of that feature ... should be a simple fix, just adding a check for rows <= 3 and switch texture if so ...
