### ISSUE TITLE
Syncing issues, in general?

### ISSUE THREAD

**Issue by Boden-C** [samolego/ClientStorage#12]
I don't know if I'm doing something wrong, but in general, input items both from the menu and from the chest cause syncing issues which break taking any unsynched items out.

Tested in Singleplayer, Paper Server, and Vanilla server with Cache Container enabled and disabled.
Item Transfer settings were also enabled and disabled for container testing
Tested with only fabric API mod and Yet Another Config and the bugs still persisted (in the video I had performance and visual mods)

This video shows most of the bugs, in chronological order:
Input to the menu doesn't work in any way I tested, causing syncing issues
Taking the unsynched items away causes glitches
Putting items into the chest sometimes rechecks, causing duplication visual glitches and syncing issues (sometimes it doesn't recheck and doubles only once, still unsynced though)
(Not shown) Taking the unsynched items away also causes glitches
Taking the items away from the container directly doesn't correctly update the menu if unsynced
https://user-images.githubusercontent.com/70297682/198537801-e4e4dbd1-e51a-490e-8c9e-a0b46316385b.mp4

Hard to make it actually work, but when it does sync correctly (rarely works when putting items into the container), taking items out from the container works fine. Item transfer is still sometimes buggy as it sometimes drags; sometimes goes straight into inventory; sometimes goes into inventory, and then clicks again and now you are dragging a different item (possibly due to syncing issues though). If this is too complicated, there should be a setting to just put straight it in the inventory to avoid this bug.
https://user-images.githubusercontent.com/70297682/198537760-ae6ee768-d1c2-4946-a818-25d288b50c08.mp4

**Comment by samolego** [comment]
Have you tried with single chest only? Double chests are known to cause trouble with the mod :P.

**Comment by Boden-C** [comment]
That actually makes a lot of sense, should probably put a warning then.
