### ISSUE TITLE
Config button

### ISSUE THREAD

**Issue by VerweliuS** [samolego/ClientStorage#13]
Versions 1.3.0 and 1.2.1 doesnt have open config button in modmenu(1.2.0 is okay)

**Comment by samolego** [comment]
Huh ... I'm sure I haven't touched modmenu ... for now you could use a keybind

**Comment by VerweliuS** [comment]
> Huh ... I'm sure I haven't touched modmenu ... for now you could use a keybind

Thanks, I completely forgot about this hotkey

**Comment by VerweliuS** [comment]
It turns out that the settings hotkey crashes the game...

> > Huh ... I'm sure I haven't touched modmenu ... for now you could use a keybind
> 
> Thanks, I completely forgot about this hotkey

**Comment by samolego** [comment]
Could you post the crash log please? Have you installed yacl?
