### ISSUE TITLE
Cant put items in a storage

### ISSUE THREAD

**Issue by VerweliuS** [samolego/ClientStorage#14]
When you try to put some items into storage it will only scans for chest that aren't empty, so if there's a lot of empty chests nearby it will just say that there no freespace containers found

**Comment by samolego** [comment]
Could you please send a video explanation?

**Comment by VerweliuS** [comment]
> Could you please send a video explanation?


https://user-images.githubusercontent.com/106067576/198865714-a83ab518-438a-4e31-9d6e-cc970078b950.mp4

**Comment by M1kep** [comment]
Seeing this in single player as well, was able to fix it locally be changing:
https://github.com/samolego/ClientStorage/blob/a822f3aecdb4e3c301a9fad8ee91fb6cc45669db/fabric-client/src/main/java/org/samo_lego/clientstorage/fabric_client/event/ContainerDiscovery.java#L132-L147

to

```java
if (!singleplayer && (container.isEmpty() || !config.enableCaching)) {
    getLogger(MOD_ID).info("Container: isEmpty -> " + container.isEmpty());
    INTERACTION_Q.add(position);
    FREE_SPACE_CONTAINERS.put(position, container.getContainerSize());
} else if(container.isEmpty()) {
  FREE_SPACE_CONTAINERS.put(position, container.getContainerSize());
} else if (!container.isEmpty()) {
    for (int i = 0; i < container.getContainerSize(); ++i) {
        ItemStack stack = container.getItem(i);
        if (!stack.isEmpty()) {
            ContainerDiscovery.addRemoteItem(blockEntity, i, stack);
        } else {
            FREE_SPACE_CONTAINERS.compute(position, (key, value) -> value == null ? 1 : value + 1);
        }
    }
}
```

I _assume_, the INTERACTION_Q isn't need locally, but not really sure. Just know that adding the second else if, resolved the empty issue
