### ISSUE TITLE
Inconsistent/Buggy behavior

### ISSUE THREAD

**Issue by M1kep** [samolego/ClientStorage#15]
Not really sure what's going on here, but the behavior is quite inconsistent for me

https://streamable.com/4c50rd

Modlist
![image](https://user-images.githubusercontent.com/2661819/198910414-999cdd70-2ce2-485e-8249-8a8ac927ef0d.png)

**Comment by samolego** [comment]
That's mostly due to double chests I'd say.

**Comment by samolego** [comment]
That's due to wrong code for pickup items.

Double chests do not work.

**Comment by M1kep** [comment]
There are double chests int he showcase in the README. Also not sure why this would be closed if it's an issue....

**Comment by M1kep** [comment]
@samolego Looks like the issue occurs when there is a hopper with it's internal storage completely full

**Comment by samolego** [comment]
Wait I didn't mean to close this 🤔 ... Probably misclicked yesterday.

Oh, you're right ... The discovery system was recoded since then (it was quite buggy before) but it broke double chests fully.

**Comment by samolego** [comment]
Tbh code for picking up items should be removed until I find a better sollution :) ...

**Comment by M1kep** [comment]
Ah makes sense! Was gonna take a look into this, but if you plan on reviewing/refactoring it soon I may hold off

**Comment by samolego** [comment]
Feel free to look into it, I'm currently lacking time ...
