### ISSUE TITLE
Incompatibility With InventoryTabs

### ISSUE THREAD

**Issue by iblowmymind** [samolego/ClientStorage#19]
(Mirror of: https://github.com/Andrew6rant/InventoryTabs/issues/73)
The tabs from [InventoryTabs](https://github.com/Andrew6rant/InventoryTabs) overlap with the UI inside the Crafting Table.
Adding crafting_table to the list of excluded blocks in InventoryTabs does not resolve the issue. (doesn't have any effect)

It would be much appreciated if you could look into this!

**Comment by samolego** [comment]
Yeah uhm it wasn't really designed well for compatibility. There'd also be no space to fit the tabs in? (When cs is active)

**Comment by iblowmymind** [comment]
I know, but a potential fix for this would be to disable the tabs for the crafting table only when the mod is active.
