### ISSUE TITLE
Crashing when opening a crafting table with client storage 

### ISSUE THREAD

**Issue by RMP777** [samolego/ClientStorage#20]
Tested with v 1.3.1 and v1.3.0 on 1.19.2, same crash

Only other mods enabled:
Fabric API 0.68,0-1.19.2
yacl 1.7.1

[crash-2022-12-10_18.37.06-client.txt](https://github.com/samolego/ClientStorage/files/10199997/crash-2022-12-10_18.37.06-client.txt)

**Comment by samolego** [comment]
Huh, that's really strange  ...

**Comment by 35584** [comment]
yeah it really is, i tried just about everything to fix it including reinstalling minecraft but it just doesn't seem to be working (this is an alt of my other account btw)

**Comment by unilock** [comment]
To clarify, you tested with *only* ClientStorage, YACL, and the Fabric API installed?
Is this on singleplayer, or multiplayer?
If you added other mods, would you mind adding your `mods` folder to an archive (like a ZIP file) and sharing that here? So we can more easily replicate your setup.

**Comment by unilock** [comment]
Here's some info related to that crash log (from [Yarn](https://github.com/FabricMC/yarn)):
```
class_344    = net/minecraft/client/gui/widget/TexturedButtonWidget
method_46427 = net/minecraft/client/gui/widget/ClickableWidget/getY()
class_479    = net/minecraft/client/gui/screen/ingame/CraftingScreen
method_25426 = net/minecraft/client/gui/screen/Screen/init()
```

It's saying that the class `TexturedButtonWidget.class` doesn't have the method `getY()`. Which is true - at least in 1.19.2. The relevant method wasn't mapped as `getY()` (by Yarn) until 1.19.3.

1.19.2: https://maven.fabricmc.net/docs/yarn-1.19.2+build.28/net/minecraft/client/gui/widget/ClickableWidget.html (no `getY()`)
1.19.3: https://maven.fabricmc.net/docs/yarn-1.19.3+build.3/net/minecraft/client/gui/widget/ClickableWidget.html#getY() (yes `getY()`)

This is the relevant line of code, modified with the commit adding support for 1.19.3 (https://github.com/samolego/ClientStorage/commit/9f1feeb17f1fea79d679c5b87b7dc637e0111b78):
https://github.com/samolego/ClientStorage/blob/9f1feeb17f1fea79d679c5b87b7dc637e0111b78/fabric-client/src/main/java/org/samo_lego/clientstorage/fabric_client/mixin/screen/MCraftingScreen.java#L127

***

In fact, I get the exact same crash when using ClientStorage 1.3.1 on Minecraft 1.19.2. (As opposed to CS 1.3.0 on MC 1.19.2 or CS 1.3.1 on MC 1.19.3, which both work fine.)

However, you said you encountered this crash with ClientStorage 1.3.0 as well. Unfortunately that's impossible. Are you sure you were using *CS 1.3.0* on *MC 1.19.2?*
@RMP777 @35584

**Comment by samolego** [comment]
I'd also say that it's due to wrong version combo.

**Comment by RMP777** [comment]
Yes only those 3, on multiplayer and single-player. 1.3.0 Crashes the same way, I can send the log for that later when I get home. My mods folder is using multimc on a modpack but I tested it with disabling every mod

**Comment by RMP777** [comment]
so sorry for the inconvenience, just tested again after reinstalling java with 1.3.0 and it worked perfectly
