### ISSUE TITLE
{1.19.3] Client crash on placing and opening a double chest.

### ISSUE THREAD

**Issue by ProsperCraft** [samolego/ClientStorage#21]
https://gist.github.com/ProsperCraft/7342b89f0d5d4ca71b873e770c3c4e6b

Modpack - https://www.curseforge.com/minecraft/modpacks/my-friends-play-without-mods

**Comment by samolego** [comment]
Thanks for report, hopefully I can fix it today.
1.4.0 right?

**Comment by samolego** [comment]
Oh, I see, that didn't happen in development as runtime mappings are still official ones ...
