### ISSUE TITLE
[enhancement] Highlight which chest has the item in question

### ISSUE THREAD

**Issue by bigrand** [samolego/ClientStorage#3]
I don't know how exactly this mod works, but it appears to be easily detectable by anticheats.
So, I think a cool improvement would be a toggle that disables the ability to take the item without opening the chest, and it would allow you to search through chests you've already opened (the insides of the chest are stored client-side), and when you search it, and select the item, it would show you which chest has it, and maybe even highlight the item when you open the chest.

**Comment by samolego** [comment]
The "discovery" part is more problematic than taking items out (basically what happens is that for every container an "open container" packet is sent upon opening, same as for taking items out).

I'm not that great with the rendering, that's one of the reasons I haven't decided to do this yet. Might need to look at some xray clients 😛 .

anticheat compatibility is definetely on my todo list, but I'd like to implement proper caching first.

**Comment by samolego** [comment]
I've made some changes to this. Still not perfect, but work is being done :)

**Comment by samolego** [comment]
I'm really not good at rendering, so I doubt "visual overlay" of chests containing items will be implemented.

**Comment by samolego** [comment]
Shimmer mod has helped - https://github.com/NotSoEpic/shimmer/blob/master/src/main/java/com/dindcrzy/shimmer/xray/Renderer.java :eyes: 

https://user-images.githubusercontent.com/34912839/197727118-28ef2174-f8e3-4319-b1ce-fb161399ae18.mp4
