### ISSUE TITLE
[Bug | Multiplayer]: Not being able to store / retrieve items from nearby chests

### ISSUE THREAD

**Issue by frinkifail** [samolego/ClientStorage#30]
I don't really understand debug mode things but can you atleast what the "inventory size mismatch" means and yeah I sometimes can't store and retrieve items from chests

The server also has anticheat so that maybe the problem? Also, when that bug happens, and I open the crafting table again, most of the items are gone and won't come back until I open the chest that contains the item I'm looking for

**Comment by frinkifail** [comment]
oh god now it's also happening in singleplayer

**Comment by samolego** [comment]
The mismatch means that client expected different sized inventory then the server one that was actually sent. This is a known bug.

Anticheat can interfear though ...
