### ISSUE TITLE
[Bug]gui error

### ISSUE THREAD

**Issue by 1240798440** [samolego/ClientStorage#31]
![Uploading QQ截图20230520015840.png…]()
have tried deleting other mods, and unload all resourcepacks, no luck
fabric 1.19.4-0.4.14
the latest version of this mod

**Comment by 1240798440** [comment]
dead image, uploaded it righe now https://imgloc.com/i/VykmGz

**Comment by samolego** [comment]
Uhh, seems like detection of crafting ui opening is not working ...
