### ISSUE TITLE
[bug] Cant open crafting table if there is no storage nearby.

### ISSUE THREAD

**Issue by CodeF53** [samolego/ClientStorage#4]
## Steps to reproduce:
Place a crafting table a good distance away from any chests or other storage
Right click

## Expected behavior
Crafting table screen opens

## Actual behavior
Crafting table screen NEVER opens.

## Video Demo:

https://user-images.githubusercontent.com/37855219/188787915-867e6ff6-11fb-437c-b9dd-9a7949b52eaf.mp4

**Comment by samolego** [comment]
Oh I actually didn't test it without chests :/, should be a trivial fix though. Sadly I'm quite busy atm, so might take some time.

**Comment by samolego** [comment]
Fixed in 895e7122fdf627f00f153f5a068202371befa178
